# Site settings

title: GoCN Education

description: >
  TODO: GoCN Education description.

baseurl: ""

url: ""

collections:
  books:
    output: true
    permalink: /books/:path
  tutorials:
    output: true
    permalink: /tutorials/:categories/:path

navs:
  - permalink: /
    text: 首页
    slug: home
  - permalink: /tutorials
    text: 教程
    slug: tutorials
  - permalink: /videos
    text: 视频
    slug: videos
  - permalink: /books
    text: 书籍
    slug: books
  - permalink: /articles
    text: 文章
    slug: articles
  - permalink: /resources
    text: 资源
    slug: resources

# Build settings

markdown: kramdown

theme: theme

gems:
  - jekyll-feed

exclude:
  - theme/
  - vendor/
  - deploy.sh
  - Gemfile
  - Gemfile.lock
