# Site settings

title: GoCN Education

description: >
  TODO: GoCN Education description.

baseurl: ""

url: ""

collections:
  books:
    output: true
    permalink: /books/:path
  tutorials:
    output: true
    permalink: /tutorials/:categories/:path


# Build settings

markdown: kramdown

theme: theme

gems:
  - jekyll-feed

exclude:
  - theme/
  - deploy.sh
  - Gemfile
  - Gemfile.lock
